name: control_system
description: "control_System_Web"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  multi_dropdown: ^2.1.4
  another_flushbar: ^1.12.30
  awesome_dialog: ^3.2.1
  easy_sidemenu: ^0.6.0
  hive_multiisolate: ^1.3.2
  hive_flutter: ^1.1.0
  pluto_grid: ^8.0.0
  dio_http_formatter: ^3.2.1
  hive_generator: ^2.0.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/