name: control_system
description: "Control_System_Web"
publish_to: "none"
version: 1.5.2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^14.2.7
  multi_dropdown: ^2.1.4
  another_flushbar: ^1.12.30
  easy_sidemenu: ^0.6.0
  hive_flutter: ^1.1.0
  pluto_grid: ^8.0.0
  carousel_slider: ^5.0.0
  awesome_dialog: ^3.2.1
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  universal_html: ^2.2.4
  dartz: ^0.10.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  searchable_listview: ^2.15.2
  file_picker: ^8.1.2
  csv: ^6.0.0
  enhance_stepper: ^1.0.1
  collection: ^1.18.0
  pdf: ^3.11.1
  file_saver: ^0.2.14
  url_launcher: ^6.3.0
  loading_indicator: ^3.1.1
  lottie: ^3.1.2
  transformable_list_view: ^0.6.0
  custom_theme:
    git:
      url: https://github.com/Mahmoud-Saeed-Mahmoud/custom_theme.git
      ref: v1.0.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # build_runner: ^2.4.12
  # flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/files/template.pdf

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/open-sans.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/presentation/resource_manager/
  filename: assets_manager.dart
  class_name: AssetsManager
