# Your GitHub Actions workflow file here
name: Deploy Control Sysytem to Firebase Hosting
on:
  pull_request:
    branches:
      - staging

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: subosito/flutter-action@v2.14.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Enable webframeworks experiment
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase experiments:enable webframeworks --token $FIREBASE_TOKEN

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting --token $FIREBASE_TOKEN
